spring:
  profiles:
    active: lettuce
  main:
    lazy-initialization: false

  redis:
    authCode:
      prefix: "portal:authCode:"
      expire: 120 # 验证码超期时间

logging:
  level:
    org.springframework: INFO